system:
  host: hipergator
  #host: rivanna
  dataset_root: null

experiment:
  directive: "l4"
  #directive: "a100-80gb"
  profile: ["LegoGearsDarknet"]
  template: ["yolov7-tiny"]
  val_frac: [0.15]
  num_gpus: [1]
  color_preset: [null]
  repeat: [1,2]

ee:
  identifier: "{experiment.profile}_{experiment.template}_val{experiment.val_frac}_repeat{experiment.repeat}"
